### ISSUE TITLE
not opening properlly/ OSError: source code not available

### ISSUE THREAD

**Issue by littleblack111** [archcraft-os/archcraft-theme-manager#3]
cant open it, when i tried 2 open it, it will return a oserror: source code not available(the ouptut log is below), but when i am trying 2 copy the out put (use | copy), it will work, and showed up properly(with error in terminal)
1. normally 
   system@ArchLinux    /mnt/D/C/R/archcraft-theme-manager     main !49  python main.py
[INFO   ] [Logger      ] Record log in /home/system/.kivy/logs/kivy_23-01-06_3.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/usr/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [KivyMD      ] Release 1.1.1 (installed at "/mnt/DATA/Code/Random/archcraft-theme-manager/kivymd/__init__.py")
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2(['text_pango'] ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 525.60.11'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Loader      ] using a thread pool of 2 workers
 Traceback (most recent call last):
   File "main.py", line 139, in <module>
     ThemeManager().run()
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 954, in run
     self._run_prepare()
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 923, in _run_prepare
     self.load_kv(filename=self.kv_file)
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 676, in load_kv
     default_kv_directory = dirname(getfile(self.__class__))
   File "/usr/lib/python3.10/inspect.py", line 785, in getfile
     raise OSError('source code not available')
 OSError: source code not available
2. with | copy
   system@ArchLinux    /mnt/D/C/R/archcraft-theme-manager     main !34  python main.py | copy
[INFO   ] [Logger      ] Record log in /home/system/.kivy/logs/kivy_23-01-06_2.txt
[INFO   ] [Kivy        ] v2.1.0
[INFO   ] [Kivy        ] Installed at "/usr/lib/python3.10/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.10.9 (main, Dec 19 2022, 17:35:49) [GCC 12.2.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python"
[INFO   ] [Logger      ] Purge log fired. Processing...
[INFO   ] [Logger      ] Purge finished!
[INFO   ] [Factory     ] 189 symbols loaded
[INFO   ] [KivyMD      ] Release 1.1.1 (installed at "/mnt/DATA/Code/Random/archcraft-theme-manager/kivymd/__init__.py")
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Text        ] Provider: sdl2(['text_pango'] ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'4.6.0 NVIDIA 525.60.11'>
[INFO   ] [GL          ] OpenGL vendor <b'NVIDIA Corporation'>
[INFO   ] [GL          ] OpenGL renderer <b'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60 NVIDIA'>
[INFO   ] [GL          ] Texture max size <32768>
[INFO   ] [GL          ] Texture max units <32>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Loader      ] using a thread pool of 2 workers
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[INFO   ] [GL          ] NPOT texture support is available
[ERROR  ] [Image       ] Not found </home/tdynamos/atm/default_previews/adaptive.png>
[INFO   ] [Base        ] Start application main loop
No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s.

error: Disabling module "battery" (reason: No suitable way to get current charge state)
/home/system/.config/openbox-themes/themes//wave/apply.sh:行241: openbox：未找到命令
No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s.

error: Disabling module "battery" (reason: No suitable way to get current charge state)
/home/system/.config/openbox-themes/themes//default/apply.sh:行233: openbox：未找到命令
^C[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/mnt/DATA/Code/Random/archcraft-theme-manager/main.py", line 139, in <module>
     ThemeManager().run()
   File "/usr/lib/python3.10/site-packages/kivy/app.py", line 955, in run
     runTouchApp()
   File "/usr/lib/python3.10/site-packages/kivy/base.py", line 574, in runTouchApp
     EventLoop.mainloop()
   File "/usr/lib/python3.10/site-packages/kivy/base.py", line 339, in mainloop
     self.idle()
   File "/usr/lib/python3.10/site-packages/kivy/base.py", line 379, in idle
     Clock.tick()
   File "/usr/lib/python3.10/site-packages/kivy/clock.py", line 733, in tick
     self.post_idle(ts, self.idle())
   File "/usr/lib/python3.10/site-packages/kivy/clock.py", line 689, in idle
     usleep(1000000 * sleeptime)
   File "/usr/lib/python3.10/site-packages/kivy/clock.py", line 965, in usleep
     _usleep(microseconds, self._sleep_obj)
   File "/usr/lib/python3.10/site-packages/kivy/clock.py", line 556, in _usleep
     _libc_usleep(int(microseconds))
 KeyboardInterrupt

**Comment by T-Dynamos** [comment]
```
No backlight controller was found, so we could not decide an automatic target. The current command will have no effect. Please use -L to find a target and then specify it with -s.
``` 
I dought if it is a kivy error, could you confirm you are using Archcraft?

**Comment by T-Dynamos** [comment]
Fixed in latest commit
