### ISSUE TITLE
Having trouble using the manager after following installation instructions 

### ISSUE THREAD

**Issue by L18iv** [archcraft-os/archcraft-theme-manager#8]
FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/python3.11/site-packages/kivymd/uix/label/label.kv' Is the error message, Maybe I've done something wrong?

**Comment by T-Dynamos** [comment]
Please try `pip3 uninstall kivymd && pip3 install https://github.com/kivymd/KivyMD/archive/refs/heads/master.zip` and rhen rerun?

**Comment by L18iv** [comment]
Using pip3 gives the "externally-managed-environment" error so I've used pipx instead, and no unfortunately it hasn't solved the issue, after installing it from the github page it still shows the exact same issue :|, thank you for your answer though
