### ISSUE TITLE
Cant's install via pacman

### ISSUE THREAD

**Issue by vortex64bit** [archcraft-os/archcraft-theme-manager#9]
The way you have shown how to install Kivy. It's not going along with Pacman. I am unable to install those in the way you have shown.
![Screenshot_2023-08-30-11-56-01_1366x768](https://github.com/archcraft-os/archcraft-theme-manager/assets/90128094/0141135a-ad62-44d4-9f7d-1765b9d03643)

**Comment by T-Dynamos** [comment]
Add `--break-system-packages`.

**Comment by vortex64bit** [comment]
> Add `--break-system-packages`.

Hey it's working. Thanks
